# Enhanced Celestials Fabric-only mixin toggles.

# Stops ChatScreen from closing itself when Enter/Escape is pressed if a client command (e.g. /ecc shaders) already opened a different screen.
# This is enabled by default, but can be disabled if this mixin conflicts with another mod.
ChatScreenMixin=true
